name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-db:

    runs-on: ubuntu-latest

    steps:

    - name: create database
      run: which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y ); mkdir -p ~/.ssh; eval $(ssh-agent -s); apt-get update -qq && apt-get install -y -qq sshpass; export SSHPASS=$AddressServerWebSSHPwd; sshpass -e ssh -p 22 $AddressServerWebSSH 'mysql -h berginfrofemile.mysql.db -u berginfrofemile --password=$mdpDataBase < www/web-jjb/BD/bd-create.sql '
      
      

